### ISSUE TITLE
[Question] Does temporalite have support for UI?

### ISSUE THREAD

**Issue by amartine59** [DataDog/temporalite#19]
Hi, I'd like to know if temporalite also supports Temporal Web UI or if we can only read information from the server through tctl.

**Comment by amartine59** [comment]
I found the answer on the [Community Meetup # 7](https://youtu.be/GpbOkDjpeYU?t=733) for temporal. I'm closing this now

**Comment by sw-yx** [comment]
haha thanks for watching :)

right now the UI can actually work if you run it separately on localhost, but it was hardcoded, so it doesnt work anywhere else. @jbreiding has started a PR for this https://github.com/DataDog/temporalite/pull/16

**Comment by amartine59** [comment]
Oh okay, thank you @sw-yx

**Comment by jbreiding** [comment]
This was previously possible if the processes were sharing the same "localhost".
