### ISSUE TITLE
Crashes with "duplicate proto type registered" 

### ISSUE THREAD

**Issue by vkarpov15** [DataDog/temporalite#54]
## Expected Behavior

Be able to run `temporalite start --namespace default` after installing

## Actual Behavior

Here's what I did:

```
$ go version
go version go1.18 linux/amd64
$ go install github.com/DataDog/temporalite/cmd/temporalite@latest
$ temporalite start --namespace default
2022/03/18 10:52:57 proto: duplicate proto type registered: temporal.api.workflowservice.v1.RegisterNamespaceRequest
2022/03/18 10:52:57 proto: duplicate proto type registered: temporal.api.workflowservice.v1.RegisterNamespaceRequest.DataEntry
2022/03/18 10:52:57 proto: duplicate proto type registered: temporal.api.workflowservice.v1.RegisterNamespaceResponse
2022/03/18 10:52:57 proto: duplicate proto type registered: temporal.api.workflowservice.v1.ListNamespacesRequest
2022/03/18 10:52:57 proto: duplicate proto type registered: temporal.api.workflowservice.v1.ListNamespacesResponse
```

One possibility: I previously had Go 1.16 installed and tried to install temporalite. That failed, so I upgraded to Go 1.18, installed successfully, and ran :point_up: . Maybe I need to run some command to clear some data somewhere?

## Steps to Reproduce the Problem

See bash input/output above

## Specifications

- Version: Whatever `latest` is right now
- Platform: Ubuntu 18.04

**Comment by cretz** [comment]
This is probably due to having https://github.com/temporalio/ui-server/tree/main/server/generated/api and https://github.com/temporalio/api-go in the same project.

I agree the output may be annoying, but are you sure it's crashing? I think it's just printing per https://github.com/gogo/protobuf/blob/226206f39bd7276e88ec684ea0028c18ec2c91ae/proto/properties.go#L548

**Comment by vkarpov15** [comment]
I took a closer look and it is crashing, I just didn't include the full output. Here's the actual error message:

```
2022/03/25 12:34:00 error setting up schema: unable to create SQLite admin DB: unable to open database file: no such file or directory
```

How can I fix this?

**Comment by billyshambrook** [comment]
@vkarpov15 just ran into this myself, seems like it is attempting to write the DB file in a non-existing directory. I got around this by running `temporalite start -h` and finding the default path shown against the `-f` argument.

**Comment by jlegrone** [comment]
This can probably be handled by Temporalite. Since this issue title and description aren't related to the root cause, let's move discussion to https://github.com/DataDog/temporalite/issues/55 instead.

**Comment by jlegrone** [comment]
This can probably be handled by Temporalite. Since this issue title and description aren't related to the root cause, let's move discussion to https://github.com/DataDog/temporalite/issues/55 instead.
